name: Generate ASCII Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Make Shell Script Executable
        run: chmod +x ./ascii-script.sh

      - name: Executing Shell Script
        run: ./ascii-script.sh

    #   - name: Install Cowsay Program
    #     run: sudo apt-get install cowsay -y

    #   - name: Execute Cowsay CMD
    #     run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

    #   - name: Test File Exists
    #     run: grep -i "dragon" dragon.txt

    #   - name: Read File
    #     run: cat dragon.txt

    #   - name: List Repo Files
    #     run: ls -ltra
