name: Generate ASCII Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: List Repo Files
        run: ls -ltra

      - name: Make Shell Script Executable
        run: chmod +x ./ascii-script.sh

      - name: Executing Shell Script
        run: ./ascii-script.sh
